name: Generate New Release

on: workflow_dispatch


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
