name: CI
run-name: Run CI on ${{ github.ref_name }} by @${{ github.actor }}

on: 
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  sample:
    name: Sample
    runs-on: ubuntu-20.04
    steps:
      - name: Show Ref
        run: echo ${{ github.ref }}

      - name: Conditional
        if: github.event_name == 'workflow_dispatch'
        run: echo "Workflow Dispatch detected!"

      - name: Else
        if: github.event_name != 'workflow_dispatch'
        run: echo ${{ github.event_name }}
